fields:
  - name: ASSET_HUB_ADMIN_USER_IDS
    label:
      en: Administrator
      zh: 管理员
    placeholder:
      en: Select users with admin privileges
      zh: 选择具有管理员权限的用户
    type: user_select
  - name: ASSET_HUB_APPROVER_USER_IDS
    label:
      en: Approver
      zh: 审批员
    placeholder:
      en: Select users with approver privileges
      zh: 选择具有审批权限的用户
    type: user_select
  - name: ASSET_HUB_SKIP_SEED
    label:
      en: Sample Data
      zh: 示例数据
    description:
      en: This option only takes effect on first installation
      zh: 此选项仅在首次安装时生效
    type: select
    options:
      - label:
          en: Add Sample Data
          zh: 添加示例数据
        value: false
      - label:
          en: Skip Adding Sample Data
          zh: 跳过添加示例数据
        value: true
    default: false
menu_items:
  - location: application
    label:
      en: Assets
      zh: 资产管理
    url: "apps/asset-hub/{system_lang}?theme={system_theme}"
    url_type: iframe
    background: "#ffffff|#0a0a0a"