fields:
  - name: ASSET_HUB_ADMIN_USER_IDS
    label:
      en: Administrator
      zh: 管理员
    placeholder:
      en: Select users with admin privileges
      zh: 选择具有管理员权限的用户
    type: user_select
  - name: ASSET_HUB_APPROVER_USER_IDS
    label:
      en: Approver
      zh: 审批员
    placeholder:
      en: Select users with approver privileges
      zh: 选择具有审批权限的用户
    type: user_select
menu_items:
  - location: application
    label:
      en: Assets
      zh: 资产管理
    url: "apps/asset-hub/{system_lang}?theme={system_theme}"
    url_type: iframe
    background: "#ffffff|#0a0a0a"